meta:
    site_title: "狂飙蜗牛"
    site_subtitle: "兼职程序员"
    site_language: "zh_CN"
    absolute_baseurl: http://kissliux.github.io/
    domain: kissliux.github.io
    author:
        full_name: 刘 兴
        short_name: shane
        name: shane
        email: kissliux@qq.com

url: http://kissliux.github.io/

baseurl: /

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /blog/:year/:month/:day/:title

disqus_short_name: shaneLau

      
css:
    - css/screen.css


