meta:
    site_title: "一个放荡不羁的程序员"
    site_subtitle: "我的心是旷远的鸟，在你的眼中找到了天空！"
    site_language: "zh_CN"
    absolute_baseurl: http://kissliux.github.io/
    domain: kissliux.github.io
    author:
        full_name: 刘兴
        short_name: shane
        name: shane
        email: kissliux@qq.com

url: http://kissliux.github.io/

baseurl: /

markdown: kramdown

pygments: false

permalink: /blog/:year/:month/:day/:title

disqus_short_name: shaneLau

css:
    - css/screen.css


